### ISSUE TITLE
Insert without choosing an image 

### ISSUE THREAD

**Issue by Jorge-Collado** [BryanJT01/Gestion_Arte#1]
When you click the "insertar" button on the insert dialog if you didn't an image the program will print an ImageIOException, that's not cool. You should try to make a default image to use it if the user doesn't choose an image
![image](https://user-images.githubusercontent.com/77398684/140787653-8918875e-2d40-45f7-bab4-614323008bce.png)

ImagePath it's previously initialiazed with the path of the default image, so if the user didn't choose his value won't change

**Comment by BryanJT01** [comment]
The method that i finally used is less effective, but I tried to use your code and it did´t  work correctly
