### ISSUE TITLE
Update error even when the data is correct

### ISSUE THREAD

**Issue by Jorge-Collado** [BryanJT01/Gestion_Arte#2]
Selecciono una obra de la lista
![image](https://user-images.githubusercontent.com/77398684/141136977-31ca22d1-bae4-4566-b3a5-8c14e83e48e1.png)

Y hago doble o la busco en el update y la modifico con información valida
![image](https://user-images.githubusercontent.com/77398684/141137367-e11f3b81-c2c6-448e-861d-f1b531f9206e.png)

Lo que pasa es que al darle al boton de update me encuentro con esto
![image](https://user-images.githubusercontent.com/77398684/141139146-9030a393-35d9-4fd5-bf62-a67ef97c000c.png)

Basicamente te has confundido al asignar el texto y en lugar de ponerle el texto de la "lblCodigo" le has puesto el de la "lblRegistro" asi que al actualizar te pone siempre como registro "REGISTRO IB"
![image](https://user-images.githubusercontent.com/77398684/141140682-158f9986-d0f9-4fc5-89b0-a3d9fb58e49d.png)

**Comment by BryanJT01** [comment]
This error was corrected in the last version of the last issue
